baseURL = "https://larsgraubner.com/"
languageCode = "en-US"
title = "Lars Graubner"

sectionPagesMenu = "main"
paginate = 15
disableHugoGeneratorInject = true
enableGitInfo = true

pluralizeListTitles = false

copyright = "© 2021 Lars Graubner. All rights reserved."

enableRobotsTXT = true

[taxonomies]
category = "categories"

[markup]
[markup.highlight]
style = "github"

[author]
name = "Lars Graubner"

[params]
description = "Ramblings about daily web development encounters."
